version: '3'
services:
  mongo:
    image: "mongo:4.2"
  api:
    build: api
    depends_on:
      - mongo
    ports:
      - "8081:8080"
    environment:
      MONGO_URL: "mongodb://mongo:27017/marvel"
      PORT: "8080"
    restart: always
  front:
    build:
      context: front
      args:
        - REACT_APP_API_URL=http://localhost:8081/api
    depends_on:
      - api
    ports:
      - "3000:80"
    restart: always
